apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hw-operator
  template:
    metadata:
      labels:
        name: hw-operator
    spec:
      serviceAccountName: hw-operator
      containers:
        - name: hw-operator
          image: docker.io/giladravid16/hw-operator:0.1
          command:
          - hw-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "hw-operator"
